import Catogaries from "@/components/Catogaries"
import Chefs from "@/components/Chefs"
import Hero from "@/components/Hero"
import Head from "next/head"
import Footer from "@/components/Footer"
import Hari from "@/components/Hari"

export default function Home() {
  return (
    <>
      <Head>
        <title>Pizeria | Hari-devign</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <Hero />
        <Catogaries />
        <Chefs />
        <Footer />
        <Hari />
      </main>
    </>
  )
}
